# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# exportpy.py
# Created on: 2019-04-29 09:21:14.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
stops_Oct_2018 = "stops_Oct_2018"
I_stops_Oct_2018_stop_code = stops_Oct_2018
Value = "1"
routes_Oct_2018 = "routes_Oct_2018"
routes_Oct_2018__3_ = routes_Oct_2018

# Process: Iterate Row Selection
arcpy.IterateRowSelection_mb(stops_Oct_2018, "stop_code #", "true")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(routes_Oct_2018, "WITHIN_A_DISTANCE", I_stops_Oct_2018_stop_code, "25 Feet", "NEW_SELECTION", "NOT_INVERT")

